project:
  type: website
  output-dir: _site
  resources:
    - R/statistical_reports/*.docx

website:
  title: "Pika-Yak Interactions"
  navbar:
    left:
      - text: "Home"
        href: R/statistical_reports/index.qmd
      - text: "Methods and Results"
        href: R/statistical_reports/manuscript_figures_and_text.qmd
      - text: "Exploratory Reports"
        menu:
          - text: "Diet Selection"
            href: R/statistical_reports/diet_selection_report.qmd
          - text: "Plant Cover"
            href: R/statistical_reports/experiment_plant_cover.qmd
          - text: "Foraging Efficiency"
            href: R/statistical_reports/experiment_foraging_efficiency.qmd
          - text: "Forage Quality"
            href: R/statistical_reports/experiment_forage_quality.qmd

format:
  html:
    theme: cosmo
    toc: true